trigger:
- adding-docker

resources:
- repo: self

variables:
  imageName: 'rafiktaamma/chat-bot'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(imageName):$(tag)

    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'dockerHubServiceConnection'

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        tags: |
          $(imageName):$(tag)

    - script: |
        docker logout
      displayName: Logout from Docker Hub